### ISSUE TITLE
Stream was too long

### ISSUE THREAD

**Issue by cjnunn88** [GewoonJaap/WinWhisper#11]
Hi,

I just installed, and tried to run a test against one file, and I keep getting this error. Did I miss something during installation?

Error details:
========== Start Of Error ==========
Error name:
IOException
Error message:
Stream was too long.
Error stacktrace:
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at AudioExtractor.Extractor.ExtractAudioFromVideoFile(String videoFilePath)
   at Program.<>c__DisplayClass0_0.<<Main>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Utility.LoopUtil.ForEachAsync[T](List`1 list, Func`2 func)
   at Program.Main(String[] args)
Error inner exception:

Error inner exception stacktrace:

========== End Of Error ==========

**Comment by GewoonJaap** [comment]
Could you give me the following info?
How long was the video?
What is the size of the video in in GB?
How much Ram do you have in GB?

**Comment by cjnunn88** [comment]
> Could you give me the following info? How long was the video? What is the size of the video in in GB? How much Ram do you have in GB?

Sure thing.

Video Length: 00:42:01
Video Size: 4.62GB
RAM: 12GB

**Comment by GewoonJaap** [comment]
Thanks for providing me with the information. I will try to see what might cause this issue and try to fix it.
