### ISSUE TITLE
How to solve Fatal error. System.Runtime.InteropServices.SEHException (0x80004005)?

### ISSUE THREAD

**Issue by PClow165** [GewoonJaap/WinWhisper#5]
Hello I tried everything and still am not able to solve it at windows 11

Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
Repeat 2 times:
--------------------------------
   at Whisper.net.Native.NativeMethods.whisper_full_with_state(IntPtr, IntPtr, Whisper.net.Native.WhisperFullParams, IntPtr, Int32)
--------------------------------
   at Whisper.net.WhisperProcessor+<>c__DisplayClass27_0.<ProcessInternalAsync>b__0()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)

**Comment by GewoonJaap** [comment]
I will look into this.
